import type { CodegenConfig } from "./config.js";
import type { ControllerIR, OperationIR, ParamIR } from "./types.js";
import { indent, pascalCase, propertyKey } from "./utils.js";

const HEADER = `// AUTO-GENERATED by swagger-to-tanstack-query. Do not edit by hand.\n`;

interface ErrorTypeInfo {
  /** TError expression, e.g. `AxiosError<ApiError>`; null when no error config. */
  type: string | null;
  /** Import lines required by `type`, or "" when none. */
  imports: string;
}

/** Build the configured error type (`AxiosError<T>`) and its imports. */
function errorTypeInfo(config: CodegenConfig): ErrorTypeInfo {
  if (!config.error) return { type: null, imports: "" };
  const local = config.error.name === "default" ? "ApiError" : config.error.name;
  const errImport =
    config.error.name === "default"
      ? `import type ${local} from "${config.error.path}";\n`
      : `import type { ${local} } from "${config.error.path}";\n`;
  return {
    type: `AxiosError<${local}>`,
    imports: `import type { AxiosError } from "axios";\n${errImport}`,
  };
}

/** Describes one argument of a generated api function. */
interface Input {
  name: string;
  tsType: string;
  optional: boolean;
}

/** A `{ key: T; ... }` object type whose keys are the params' real wire names. */
function paramObjectType(params: ParamIR[]): string {
  const shape = params
    .map((p) => `${propertyKey(p.name)}${p.required ? "" : "?"}: ${p.tsType}`)
    .join("; ");
  return `{ ${shape} }`;
}

/**
 * Ordered inputs for an operation: path params (positional), then body, then a
 * `params` object, then a `headers` object. Query/header objects keep the real
 * wire names as keys so axios serializes them correctly.
 */
function operationInputs(op: OperationIR): Input[] {
  const inputs: Input[] = [];
  for (const p of op.pathParams) {
    inputs.push({ name: p.safeName, tsType: p.tsType, optional: false });
  }
  if (op.requestBodyType) {
    inputs.push({ name: "body", tsType: op.requestBodyType, optional: false });
  }
  if (op.queryParams.length > 0) {
    inputs.push({
      name: "params",
      tsType: paramObjectType(op.queryParams),
      optional: op.queryParams.every((q) => !q.required),
    });
  }
  if (op.headerParams.length > 0) {
    inputs.push({
      name: "headers",
      tsType: paramObjectType(op.headerParams),
      optional: op.headerParams.every((h) => !h.required),
    });
  }
  return inputs;
}

/** The runtime URL template with path params interpolated. */
function urlExpr(op: OperationIR): string {
  let path = op.path;
  for (const p of op.pathParams) {
    path = path.split(`{${p.name}}`).join(`\${${p.safeName}}`);
  }
  return `\`${path}\``;
}

/** `{ a: T; b?: U }` object type for all of an operation's inputs. */
function inputsObjectType(inputs: Input[]): string {
  const shape = inputs.map((i) => `${i.name}${i.optional ? "?" : ""}: ${i.tsType}`).join("; ");
  return `{ ${shape} }`;
}

/** Comma-separated input names, e.g. `id, body, params`. */
function inputNames(inputs: Input[]): string {
  return inputs.map((i) => i.name).join(", ");
}

/** JSDoc block from `summary` + `@deprecated`. */
function jsdoc(op: OperationIR): string {
  const lines: string[] = [];
  if (op.summary) lines.push(op.summary.replace(/\*\//g, "*\\/"));
  if (op.deprecated) lines.push("@deprecated");
  if (lines.length === 0) return "";
  if (lines.length === 1) return `/** ${lines[0]} */\n`;
  return `/**\n${lines.map((l) => ` * ${l}`).join("\n")}\n */\n`;
}

/** axios request `config` arg ({ params, headers }) or "" when none. */
function configArgExpr(op: OperationIR): string {
  const props: string[] = [];
  if (op.queryParams.length) props.push("params");
  if (op.headerParams.length) props.push("headers");
  return props.length ? `{ ${props.join(", ")} }` : "";
}

/** All declared type names referenced anywhere in `blob`, for import lists. */
function importsForBlob(controller: ControllerIR, blob: string): string[] {
  return controller.types
    .map((t) => t.name)
    .filter((name) => new RegExp(`\\b${name}\\b`).test(blob));
}

// ---------------------------------------------------------------------------
// types.ts
// ---------------------------------------------------------------------------

export function generateTypes(controller: ControllerIR): string {
  if (controller.types.length === 0) {
    return `${HEADER}export {};\n`;
  }
  const body = controller.types.map((t) => t.code).join("\n\n");
  return `${HEADER}${body}\n`;
}

// ---------------------------------------------------------------------------
// apis.ts
// ---------------------------------------------------------------------------

export function generateApis(controller: ControllerIR, config: CodegenConfig): string {
  const clientImport =
    config.client.name === "default"
      ? `import client from "${config.client.path}";`
      : `import { ${config.client.name} as client } from "${config.client.path}";`;

  const fns = controller.operations
    .map((op) => apiFn(op, config.response.dataField))
    .join("\n\n");
  const typeBlob = controller.operations.map(apiTypeBlob).join(" ");
  const typeNames = importsForBlob(controller, typeBlob);
  const typeImport = typeNames.length ? `import type { ${typeNames.join(", ")} } from "./types";\n` : "";
  const envelopeImport = envelopeImportFor(controller, config);

  return `${HEADER}${clientImport}\n${envelopeImport}${typeImport}\n${fns}\n`;
}

/** Import the generic envelope type when this controller's responses use it. */
function envelopeImportFor(controller: ControllerIR, config: CodegenConfig): string {
  const env = config.response.envelope;
  if (!env) return "";
  const local = env.name === "default" ? "CommonResponse" : env.name;
  const used = controller.operations.some((op) => op.responseType.includes(`${local}<`));
  if (!used) return "";
  return env.name === "default"
    ? `import type ${local} from "${env.path}";\n`
    : `import type { ${local} } from "${env.path}";\n`;
}

/** Every TS type referenced in an operation's api signature. */
function apiTypeBlob(op: OperationIR): string {
  return [
    op.responseType,
    op.requestBodyType,
    ...op.pathParams.map((p) => p.tsType),
    ...op.queryParams.map((p) => p.tsType),
    ...op.headerParams.map((p) => p.tsType),
  ].join(" ");
}

function apiFn(op: OperationIR, dataField: string | null): string {
  const inputs = operationInputs(op);
  // Single destructured object argument: { id, body, params, headers }.
  const sig = inputs.length ? `{ ${inputNames(inputs)} }: ${inputsObjectType(inputs)}` : "";
  const resp = op.responseType;
  const url = urlExpr(op);
  const hasBody = op.method === "post" || op.method === "put" || op.method === "patch";
  const configArg = configArgExpr(op);
  // Unwrap the common envelope field when configured and present on this response.
  const access = op.responseUnwrap && dataField ? `res.data.${dataField}` : "res.data";
  const doc = jsdoc(op);

  // multipart/form-data: build a FormData from the body object.
  if (op.requestBodyMultipart) {
    const args = [url, "formData", configArg].filter(Boolean).join(", ");
    return (
      `${doc}export const ${op.name} = (${sig}) => {\n` +
      `  const formData = new FormData();\n` +
      `  Object.entries(body).forEach(([key, value]) => {\n` +
      `    if (value === undefined || value === null) return;\n` +
      `    formData.append(key, value instanceof Blob ? value : String(value));\n` +
      `  });\n` +
      `  return client.${op.method}<${resp}>(${args}).then((res) => ${access});\n` +
      `};`
    );
  }

  let call: string;
  if (hasBody) {
    const bodyArg = op.requestBodyType ? "body" : "undefined";
    const args = [url, bodyArg, configArg].filter(Boolean).join(", ");
    call = `client.${op.method}<${resp}>(${args})`;
  } else {
    const args = [url, configArg].filter(Boolean).join(", ");
    call = `client.${op.method}<${resp}>(${args})`;
  }

  return `${doc}export const ${op.name} = (${sig}) =>\n  ${call}.then((res) => ${access});`;
}

// ---------------------------------------------------------------------------
// queries.ts  (queryOptions pattern, TanStack Query v5)
// ---------------------------------------------------------------------------

export function generateQueries(controller: ControllerIR, config: CodegenConfig): string {
  const queries = controller.operations.filter((op) => op.kind === "query");
  if (queries.length === 0) {
    return `${HEADER}export {};\n`;
  }

  const err = errorTypeInfo(config);
  const objectName = `${camelLower(controller.pascalName)}Queries`;
  const entries = queries.map((op) => queryEntry(controller, op, err.type)).join("\n");

  const typeBlob = queries.map(paramTypeBlob).join(" ");
  const typeNames = importsForBlob(controller, typeBlob);
  const typeImport = typeNames.length ? `import type { ${typeNames.join(", ")} } from "./types";\n` : "";

  return (
    `${HEADER}import { queryOptions } from "@tanstack/react-query";\n` +
    `${err.imports}import * as apis from "./apis";\n${typeImport}\n` +
    `export const ${objectName} = {\n${indent(entries)}\n};\n`
  );
}

/** TS types referenced by an operation's path/query/header params. */
function paramTypeBlob(op: OperationIR): string {
  return [
    ...op.pathParams.map((p) => p.tsType),
    ...op.queryParams.map((p) => p.tsType),
    ...op.headerParams.map((p) => p.tsType),
  ].join(" ");
}

function queryEntry(controller: ControllerIR, op: OperationIR, errorType: string | null): string {
  const inputs = operationInputs(op);
  const hasArgs = inputs.length > 0;
  const sig = hasArgs ? `args: ${inputsObjectType(inputs)}` : "";
  const callArg = hasArgs ? "args" : "";

  const keyParts = [JSON.stringify(controller.dirName), JSON.stringify(op.name)];
  if (hasArgs) keyParts.push("args");
  const queryKey = `[${keyParts.join(", ")}]`;

  // Explicit generics so the configured error type flows to useQuery's `error`.
  const generics = errorType
    ? `<Awaited<ReturnType<typeof apis.${op.name}>>, ${errorType}>`
    : "";

  return (
    `${jsdoc(op)}${op.name}: (${sig}) =>\n` +
    `  queryOptions${generics}({\n` +
    `    queryKey: ${queryKey},\n` +
    `    queryFn: () => apis.${op.name}(${callArg}),\n` +
    `  }),`
  );
}

// ---------------------------------------------------------------------------
// mutations.ts  (useMutation hooks)
// ---------------------------------------------------------------------------

export function generateMutations(controller: ControllerIR, config: CodegenConfig): string {
  const mutations = controller.operations.filter((op) => op.kind === "mutation");
  if (mutations.length === 0) {
    return `${HEADER}export {};\n`;
  }

  const err = errorTypeInfo(config);
  const errorType = err.type ?? "DefaultError";
  const hooks = mutations.map((op) => mutationHook(op, errorType)).join("\n\n");
  const typeBlob = mutations
    .map((op) => `${op.requestBodyType ?? ""} ${paramTypeBlob(op)}`)
    .join(" ");
  const typeNames = importsForBlob(controller, typeBlob);
  const typeImport = typeNames.length ? `import type { ${typeNames.join(", ")} } from "./types";\n` : "";

  // `DefaultError` is only needed as a fallback when no error type is configured.
  const tanstackTypeImport = err.type
    ? `import type { UseMutationOptions } from "@tanstack/react-query";\n`
    : `import type { DefaultError, UseMutationOptions } from "@tanstack/react-query";\n`;

  return (
    `${HEADER}import { useMutation } from "@tanstack/react-query";\n` +
    `${tanstackTypeImport}${err.imports}import * as apis from "./apis";\n${typeImport}\n${hooks}\n`
  );
}

function mutationHook(op: OperationIR, errorType: string): string {
  const hookName = `use${pascalCase(op.name)}`;
  const inputs = operationInputs(op);
  const hasArgs = inputs.length > 0;

  // The mutation's `variables` IS the api's single object argument.
  const varsType = hasArgs ? inputsObjectType(inputs) : "void";
  const variables = hasArgs ? `(vars: ${varsType})` : "()";
  const callArg = hasArgs ? "vars" : "";

  const dataType = `Awaited<ReturnType<typeof apis.${op.name}>>`;
  const optionsType = `Omit<UseMutationOptions<${dataType}, ${errorType}, ${varsType}>, "mutationFn">`;

  return (
    `${jsdoc(op)}export const ${hookName} = (options?: ${optionsType}) =>\n` +
    `  useMutation({\n` +
    `    mutationFn: ${variables} => apis.${op.name}(${callArg}),\n` +
    `    ...options,\n` +
    `  });`
  );
}

// ---------------------------------------------------------------------------
// index.ts  (controller barrel)
// ---------------------------------------------------------------------------

export function generateIndex(): string {
  return (
    `${HEADER}export * from "./types";\n` +
    `export * from "./apis";\n` +
    `export * from "./queries";\n` +
    `export * from "./mutations";\n`
  );
}

function camelLower(pascal: string): string {
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}
