import type { ResolvedConfig } from "./config.js";
import type { ControllerIR, OperationIR } from "./types.js";
import { indent, pascalCase } from "./utils.js";

const HEADER = `// AUTO-GENERATED by swagger-tanstack-builder. Do not edit by hand.\n`;

interface ErrorTypeInfo {
  /** TError expression, e.g. `AxiosError<ApiError>`; null when no error config. */
  type: string | null;
  /** Import lines required by `type`, or "" when none. */
  imports: string;
}

/** Build the configured error type (`AxiosError<T>`) and its imports. */
function errorTypeInfo(config: ResolvedConfig): ErrorTypeInfo {
  if (!config.error) return { type: null, imports: "" };
  const local = config.error.name === "default" ? "ApiError" : config.error.name;
  const errImport =
    config.error.name === "default"
      ? `import type ${local} from "${config.error.path}";\n`
      : `import type { ${local} } from "${config.error.path}";\n`;
  return {
    type: `AxiosError<${local}>`,
    imports: `import type { AxiosError } from "axios";\n${errImport}`,
  };
}

/** Describes one argument of a generated api function. */
interface Input {
  name: string;
  tsType: string;
  optional: boolean;
}

/** Ordered inputs for an operation: path params, then body, then a query object. */
function operationInputs(op: OperationIR): Input[] {
  const inputs: Input[] = [];
  for (const p of op.pathParams) {
    inputs.push({ name: p.safeName, tsType: p.tsType, optional: false });
  }
  if (op.requestBodyType) {
    inputs.push({ name: "body", tsType: op.requestBodyType, optional: false });
  }
  if (op.queryParams.length > 0) {
    const allOptional = op.queryParams.every((q) => !q.required);
    const shape = op.queryParams
      .map((q) => `${q.safeName}${q.required ? "" : "?"}: ${q.tsType}`)
      .join("; ");
    inputs.push({ name: "params", tsType: `{ ${shape} }`, optional: allOptional });
  }
  return inputs;
}

/** The runtime URL template with path params interpolated. */
function urlExpr(op: OperationIR): string {
  let path = op.path;
  for (const p of op.pathParams) {
    path = path.replace(`{${p.name}}`, `\${${p.safeName}}`);
  }
  return `\`${path}\``;
}

/** All declared type names referenced anywhere in `blob`, for import lists. */
function importsForBlob(controller: ControllerIR, blob: string): string[] {
  return controller.types
    .map((t) => t.name)
    .filter((name) => new RegExp(`\\b${name}\\b`).test(blob));
}

// ---------------------------------------------------------------------------
// types.ts
// ---------------------------------------------------------------------------

export function generateTypes(controller: ControllerIR): string {
  if (controller.types.length === 0) {
    return `${HEADER}export {};\n`;
  }
  const body = controller.types.map((t) => t.code).join("\n\n");
  return `${HEADER}${body}\n`;
}

// ---------------------------------------------------------------------------
// apis.ts
// ---------------------------------------------------------------------------

export function generateApis(controller: ControllerIR, config: ResolvedConfig): string {
  const clientImport =
    config.client.name === "default"
      ? `import client from "${config.client.path}";`
      : `import { ${config.client.name} as client } from "${config.client.path}";`;

  const fns = controller.operations
    .map((op) => apiFn(op, config.response.dataField))
    .join("\n\n");
  const typeBlob = controller.operations
    .map((op) => [op.responseType, op.requestBodyType, ...op.pathParams.map((p) => p.tsType), ...op.queryParams.map((p) => p.tsType)].join(" "))
    .join(" ");
  const typeNames = importsForBlob(controller, typeBlob);
  const typeImport = typeNames.length ? `import type { ${typeNames.join(", ")} } from "./types";\n` : "";

  return `${HEADER}${clientImport}\n${typeImport}\n${fns}\n`;
}

function apiFn(op: OperationIR, dataField: string | null): string {
  const inputs = operationInputs(op);
  const sig = inputs.map((i) => `${i.name}${i.optional ? "?" : ""}: ${i.tsType}`).join(", ");
  const resp = op.responseType;
  const url = urlExpr(op);
  const hasBody = op.method === "post" || op.method === "put" || op.method === "patch";
  const configArg = op.queryParams.length ? "{ params }" : "";

  let call: string;
  if (hasBody) {
    const bodyArg = op.requestBodyType ? "body" : "undefined";
    const args = [url, bodyArg, configArg].filter(Boolean).join(", ");
    call = `client.${op.method}<${resp}>(${args})`;
  } else {
    const args = [url, configArg].filter(Boolean).join(", ");
    call = `client.${op.method}<${resp}>(${args})`;
  }

  // Unwrap the common envelope field when configured and present on this response.
  const access = op.responseUnwrap && dataField ? `res.data.${dataField}` : "res.data";
  const doc = op.summary ? `/** ${op.summary.replace(/\*\//g, "*\\/")} */\n` : "";
  return `${doc}export const ${op.name} = (${sig}) =>\n  ${call}.then((res) => ${access});`;
}

// ---------------------------------------------------------------------------
// queries.ts  (queryOptions pattern, TanStack Query v5)
// ---------------------------------------------------------------------------

export function generateQueries(controller: ControllerIR, config: ResolvedConfig): string {
  const queries = controller.operations.filter((op) => op.kind === "query");
  if (queries.length === 0) {
    return `${HEADER}export {};\n`;
  }

  const err = errorTypeInfo(config);
  const objectName = `${camelLower(controller.pascalName)}Queries`;
  const entries = queries.map((op) => queryEntry(controller, op, err.type)).join("\n");

  const typeBlob = queries
    .map((op) => [...op.pathParams.map((p) => p.tsType), ...op.queryParams.map((p) => p.tsType)].join(" "))
    .join(" ");
  const typeNames = importsForBlob(controller, typeBlob);
  const typeImport = typeNames.length ? `import type { ${typeNames.join(", ")} } from "./types";\n` : "";

  return (
    `${HEADER}import { queryOptions } from "@tanstack/react-query";\n` +
    `${err.imports}import * as apis from "./apis";\n${typeImport}\n` +
    `export const ${objectName} = {\n${indent(entries)}\n};\n`
  );
}

function queryEntry(controller: ControllerIR, op: OperationIR, errorType: string | null): string {
  const inputs = operationInputs(op);
  const sig = inputs.map((i) => `${i.name}${i.optional ? "?" : ""}: ${i.tsType}`).join(", ");
  const callArgs = inputs.map((i) => i.name).join(", ");

  const keyParts = [JSON.stringify(controller.dirName), JSON.stringify(op.name), ...inputs.map((i) => i.name)];
  const queryKey = `[${keyParts.join(", ")}]`;

  // Explicit generics so the configured error type flows to useQuery's `error`.
  const generics = errorType
    ? `<Awaited<ReturnType<typeof apis.${op.name}>>, ${errorType}>`
    : "";

  return (
    `${op.name}: (${sig}) =>\n` +
    `  queryOptions${generics}({\n` +
    `    queryKey: ${queryKey},\n` +
    `    queryFn: () => apis.${op.name}(${callArgs}),\n` +
    `  }),`
  );
}

// ---------------------------------------------------------------------------
// mutations.ts  (useMutation hooks)
// ---------------------------------------------------------------------------

export function generateMutations(controller: ControllerIR, config: ResolvedConfig): string {
  const mutations = controller.operations.filter((op) => op.kind === "mutation");
  if (mutations.length === 0) {
    return `${HEADER}export {};\n`;
  }

  const err = errorTypeInfo(config);
  const errorType = err.type ?? "DefaultError";
  const hooks = mutations.map((op) => mutationHook(op, errorType)).join("\n\n");
  const typeBlob = mutations
    .map((op) => [op.requestBodyType, ...op.pathParams.map((p) => p.tsType), ...op.queryParams.map((p) => p.tsType)].join(" "))
    .join(" ");
  const typeNames = importsForBlob(controller, typeBlob);
  const typeImport = typeNames.length ? `import type { ${typeNames.join(", ")} } from "./types";\n` : "";

  // `DefaultError` is only needed as a fallback when no error type is configured.
  const tanstackTypeImport = err.type
    ? `import type { UseMutationOptions } from "@tanstack/react-query";\n`
    : `import type { DefaultError, UseMutationOptions } from "@tanstack/react-query";\n`;

  return (
    `${HEADER}import { useMutation } from "@tanstack/react-query";\n` +
    `${tanstackTypeImport}${err.imports}import * as apis from "./apis";\n${typeImport}\n${hooks}\n`
  );
}

function mutationHook(op: OperationIR, errorType: string): string {
  const hookName = `use${pascalCase(op.name)}`;
  const inputs = operationInputs(op);

  // (mutationFn signature, value passed to the api call, TVariables type)
  let variables: string;
  let callArgs: string;
  let varsType: string;
  if (inputs.length === 0) {
    variables = "()";
    callArgs = "";
    varsType = "void";
  } else if (inputs.length === 1) {
    const only = inputs[0];
    variables = `(${only.name}${only.optional ? "?" : ""}: ${only.tsType})`;
    callArgs = only.name;
    varsType = only.optional ? `${wrapUnion(only.tsType)} | void` : only.tsType;
  } else {
    const shape = inputs.map((i) => `${i.name}${i.optional ? "?" : ""}: ${i.tsType}`).join("; ");
    const destructure = inputs.map((i) => i.name).join(", ");
    variables = `({ ${destructure} }: { ${shape} })`;
    callArgs = destructure;
    varsType = `{ ${shape} }`;
  }

  const dataType = `Awaited<ReturnType<typeof apis.${op.name}>>`;
  const optionsType = `Omit<UseMutationOptions<${dataType}, ${errorType}, ${varsType}>, "mutationFn">`;

  const doc = op.summary ? `/** ${op.summary.replace(/\*\//g, "*\\/")} */\n` : "";
  return (
    `${doc}export const ${hookName} = (options?: ${optionsType}) =>\n` +
    `  useMutation({\n` +
    `    mutationFn: ${variables} => apis.${op.name}(${callArgs}),\n` +
    `    ...options,\n` +
    `  });`
  );
}

/** Parenthesize a union before appending ` | void`. */
function wrapUnion(type: string): string {
  return /\|/.test(type) && !type.startsWith("{") ? `(${type})` : type;
}

// ---------------------------------------------------------------------------
// index.ts  (controller barrel)
// ---------------------------------------------------------------------------

export function generateIndex(): string {
  return (
    `${HEADER}export * from "./types";\n` +
    `export * from "./apis";\n` +
    `export * from "./queries";\n` +
    `export * from "./mutations";\n`
  );
}

function camelLower(pascal: string): string {
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}
